### PR TITLE
Updates to Cloud Foundry Step

### PR DESCRIPTION
**Pull request by dlapiduz**
- Use new CF cli
- Support blue-green deploys
- Support for hosted CF instances

### CODE REVIEW

**Comment by hatchan** [comment]
Sorry for the late reaction. 

Thank you for taking the time to update this step, looks really well made :+1: 

Will take a look at merging and releasing this tomorrow

**Comment by dlapiduz** [comment]
@hatchan please let me know if you have any questions or issues!

**Comment by hatchan** [comment]
Hi, Thanks again for the PR. Did make some small changes to the code for the following reasons: 

- We try to bundle everything necessary in the step itself. So any executables are retrieved, and stored during the build step.
- We try to fix on a certain version of our dependencies.

By doing these two things, we can be (almost) certain that the step will have the same behavior, now and in the future. 

Furthermore we use shellcheck to check our `run.sh` file. 

Could you review if they cause any problems? https://github.com/wercker/step-cloud-foundry-deploy/commit/1b7d3c82af853232381d7dc3a78fb4a0424e1c1b

If you don't see any problems I'll merge it in.

**Comment by dlapiduz** [comment]
@hatchan wouldn't you have to upload the `cf` tool here to github?

Can I test the step from a branch?

**Comment by dlapiduz** [comment]
Just realized you are downloading it on the build step. :)

Anyhow, do you know any good way of testing it on my wercker file?

**Comment by hatchan** [comment]
Hey sorry, no don't have an easy way to test it. Maybe I can merge my changes with your pull request?

**Comment by dlapiduz** [comment]
@hatchan sorry for the delay. It all looks good, I just did a minor change on my end: https://github.com/dlapiduz/step-cloud-foundry-deploy/commit/235055bf08d986346e1af66cd0848aad9778a006

Could you cherry pick it?

**Pull request closed without merging**
